package by.epam.training.jwd.godot.controller.command;

public enum CommandName {
	LOGINATION, REGISTRATION, GOTOINDEXPAGE,
	LOGOUT, GOTOREGISTRATIONPAGE,GOTOLOGINATIONPAGE,GOTOADMINPAGE,
	GOTOMANAGEINGREDIENTSPAGE, MANAGEINGREDIENTS, SWITCHLANGUAGE, GOTOMANAGEUSERSPAGE, MANAGEUSERS, CREATEORDER,
	GOTOPROFILEPAGE, EDITPROFILE, GOTOCART, GOTOMANAGESPOTSPAGE, MANAGESPOT, GOTOBUYINGREDIENTS, BUYINGREDIENT,
	CARTMANAGER, CHECKORDER, GOTOCHECKORDER, GOTOMANAGEORDERS, MANAGEORDERS;
}
